services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=1234567890

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  sqlite_data: