# Generated by Django 6.0.2 on 2026-04-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_sport_type_field_open_time_field_close_time_field_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fields/'),
        ),
    ]
